name: Observe Changes in Web Page.
on:
  push:
    branches:
      - 'main'
jobs:
  observe_file_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
    
      - name: Read JSON File
        id: read_file
        run: |
          file_content=$(cat ./src/properties/homeComponent.json)
          echo "JSON_CONTENT=$file_content" >> $GITHUB_ENV

      - name: Send Webhook
        run: |
          payload=$(echo '$JSON_CONTENT' | jq -c .)
          curl -X POST -H "Content-Type: application/json" -d "${payload}" https://rowy-hooks-fdiwibo4ia-wn.a.run.app/wh/properties/gXO9N8ebsKTrbZt3JFgk