name: Observe Changes in Web Page.
on:
  push:
    branches:
      - 'main'
jobs:
  observe_file_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
    
      - name: Read file contents
        id: read_file
        run: |
          fileData=$(cat path/to/file.json)
          echo "::set-env name=FILE_DATA::$fileData"

      - name: Send data to webhook
        run: |
          curl -X POST -H "Content-Type: application/json" --data-binary "${{ env.FILE_DATA }}"  https://rowy-hooks-fdiwibo4ia-wn.a.run.app/wh/properties/gXO9N8ebsKTrbZt3JFgk