name: Observe Changes in Web Page.
on:
  push:
    branches:
      - 'main'
jobs:
  observe_file_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
    
      - name: Read file contents
        id: read_file
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const fileData = fs.readFileSync('./src/properties/homeComponent.json', 'utf8');
            console.log(fileData);
            console.log(JSON.stringify({ fileContents: fileData }));
            core.setOutput('fileContents', fileData);

      - name: Send data to webhook
        uses: actions/workflow-webhook-action@v1
        with:
          webhook_url: https://rowy-hooks-fdiwibo4ia-wn.a.run.app/wh/properties/gXO9N8ebsKTrbZt3JFgk
          payload: |
            {
              "fileData": ${{ toJSON(steps.read_file.outputs.fileContents) }}
            }