name: Observe Changes in Web Page.
on:
  push:
    branches:
      - 'main'
jobs:
  observe_file_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
    
      - name: Read file contents
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const fileData = fs.readFileSync('./src/properties/homeComponent.json', 'utf8');
            core.setOutput('fileContents', fileData);

      - name: Send Webhook
        run: |
          curl -X POST -H "Content-Type: application/json" -d "${{ steps.read_file.outputs.fileContents }}" https://rowy-hooks-fdiwibo4ia-wn.a.run.app/wh/properties/gXO9N8ebsKTrbZt3JFgk