name: Observe Changes in Web Page.
'on':
  push:
    branches:
      - main
  paths:
    - ./src
jobs:
  observe_file_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Print modified files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
      - name: Trigger Webhook
        run: >
          curl -X POST -H "Content-Type: application/json" -d '{"event":
          "trigger_event"}' <WEBHOOK_ENDPOINT>
